### PR TITLE
provide free versions of skyboxes

### PR DESCRIPTION
**Pull request by thinred**
This pull request provides free versions of textures for Gravit
so that gravit can be indeed called "Free Software".

### CODE REVIEW

**Comment by gak** [comment]
Many thanks for the effort :)

**Comment by thinred** [comment]
No worries, will you release a new version of gravit in the near future? It would be much easier for me to package it that way, but if it is not in your plans, I can package a custom distribution of last stable + free graphics.

**Comment by gak** [comment]
I made a release branch and tag for 0.5.1, but need some time to make sure it's all working, since there has been many chances since 0.5.0. I'll let you know when it's released, or in the mean time I'm happy for you to use the github zip functionality for a branch, i.e. https://github.com/gak/gravit/archive/release/0.5.1.zip

**Comment by gak** [comment]
Hi @thinred 

The development environments I use for building and testing Gravit are in shambles. Can you please create your suggested custom distribution instead of waiting for me to get things sorted?

**Comment by thinred** [comment]
Hi @gak,
I've provided a hotfix (take a look at my master branch) which bumps the last release of gravit to 0.5.1  and replaces textures just like in the develop branch. I also bumped 0.5.1 to 0.5.2 in the develop branch. I think it is fine, but you should check. I don't know precisely how you create a release tarball, but if you could do it, it'd be great. :)

**Comment by gak** [comment]
@thinred I'd rather keep with the 0.5.1 release which already which includes your changes and some other work. I also just realised I didn't push the master branch which includes the 0.5.1 release I made. The master branch is currently on par with the develop branch (following the git-flow method). I apologise about this, it caused some duplication of work! Here's a beer for compensation :) @changetip

I'll look into building a "standard" 0.5.1 release tarball in the next few days, along with some testing for previous changes, and checking out the new graphics. I'll let you know how I go.

**Comment by changetip** [comment]
Hi @thinred, you've been sent 5.4775 milli-bitcoins ($3.50) from @gak via ChangeTip. **[Collect it](https://www.changetip.com/collect/2243)**.

**[What's this?](https://www.changetip.com/tip-online/github)**

**Comment by thinred** [comment]
Thanks man! I've never used BitCoin (although I was "theoretically" aware of its workings) and I had a chance to see how it works in practice.

Let me know if you need help with working on release.

**Comment by gak** [comment]
Here you go: http://gravit.slowchop.com/media/downloads/gravit-0.5.1.tgz

I've tested the build in Linux and it works fine and the skyboxes look great! The website will be updated once I get the Windows builds out.

**Comment by FrMo** [comment]
Hi @gak seeems that you missed to update the windows iss scripts. I've fixed this in the development branch, commit 5a9add54c06c77b6ed5b70a930fc61f5bee9e815 .
@thinred nice skyboxes! If you have more of these, we could easily add them to the build-in list....

**Comment by gak** [comment]
@FrMo Apologies. I must have only looked in src. For the next release I'll make a little script to automate this.

BTW, Do you have time at the moment to make the Windows 32 and 64 bit builds?

**Comment by FrMo** [comment]
@gak not sure if I can do it during this week, but possibly during this weekend.

**Comment by gak** [comment]
@FrMo Awesome! Take your time; I'm not in a hurry :)

**Comment by FrMo** [comment]
@gak: you can pick up the windows builds from my "downloads" repository.
https://github.com/FrMo/downloads

**Pull request merged**
