### PR TITLE
windows build environment: precompiled libs, and some windows build cleanups

### PR DESCRIPTION
**Pull request by FrMo**
Hi Gerald,
I just did it ... 

this was my first try to branch/merge in my own github repo, so keep fingers crossed ..

best wishes,
  Frank.

PS: please review windows/README.txt  (I'm not a native speaker)

### CODE REVIEW

**Comment by FrMo** [comment]
I have extended this request two include the following:
- new command that puts a hard limit on the video FPS (for screensaver mode - use less CPU time)
- I just found out that gravit always crashes on XP (Win7 is OK).
  added  -mstackrealign to the gcc commandline to fix this.

**Comment by FrMo** [comment]
removed vcredist and packed all binaries into one ZIP file (as proposed in my last e-mail)

**Comment by gak** [comment]
Just looking into this now. I'm going though the VC++ build from scratch myself so I have an idea of what's involved. I'll be cherry picking many of your commits, but I probably won't merge this pull request.

I'm also considering SCons to generate the project files for VC++ so that it is easier for someone new to start developing (as it can potentially download all the dependencies and prepare include/lib paths automatically for the user).

FrMo, let me know your thoughts on this.

**Comment by FrMo** [comment]
I am very curious to discuss the experiences you will make (don't know SCons yet).

Just some quick comments: 
- Use VC++ 2008 SP1 or newer, for better Windows7 compatibility.
- My experience was that gcc (MinGW) is the best choice for "production" compilation. 
  The binaries are faster (up to 50%), and you can build native 64bit programs.
  The problem is to get precompiled 64bit DLLs for the external libs we need.

I am not sure what the benefit of SCons would be for us. Unless we add new files or required new defines, there will be no need to modify the VC++ project files. If you take a look into the files in my pull, you will see that include/lib paths are already prepared; you just need to drop the lib and header files into the right place (no need to install anything). Do you know if Scons can detect if OpenMP is availeable in VC++, and create working configurations for 32/64 bit builds ??

**Comment by gak** [comment]
SCons turned out to be lacking in generating newer versions of VC++ with a few other problems like not correctly finding cl.exe, even when it's in the path. You are correct, just setting up the project files as usual should be fine.

I had no issues creating a gravit executable in VC++ 2010 Express under Windows 7. What does VC++ 2080 SP1 do better?

I'll look at gcc soon.

**Comment by FrMo** [comment]
I have the "professional" edition of VC++ 2008 on my laptop at work, and created all Project files (*.vcproj, *.sln) with it. Just did not try the newer versions. Good to know that VC++ 2010 works with my files. Does VC++ 2010 Express have OpenMP support enabled?

If you need help in setting up MinGW gcc, just ask me. 

You can get a 64-bit gcc from the "MingGW-64" project. I am using rubenv's build of gcc 4.6.x:
http://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/rubenvb/4.6.3-1/

**Comment by gak** [comment]
@FrMo Looks like VC++ 2010 Express does not support OpenMP.

Since you're suggesting MinGW for Windows production builds, I'll focus on that.

**Comment by FrMo** [comment]
closing my request, as it is out-of sync with your main sources.

**Pull request closed without merging**
